import type { Metadata } from "next";
// import "./globals.css";
import "./output.css";
import { TopNavComponent } from "@/components/top-nav.component";
import { TopBannerComponent } from "@/components/top-banner.component";

// app/layout.tsx or pages/_app.tsx
import { Urbanist, Figtree } from "next/font/google";

const urbanist = Urbanist({
  subsets: ["latin"],
  variable: "--font-urbanist",
});

const figtree = Figtree({
  subsets: ["latin"],
  variable: "--font-figtree",
});


export const metadata: Metadata = {
  title: "Fametonic Hero",
  description: "Generated by Netzet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${urbanist.variable} ${figtree.variable} scroll-smooth`}>
      <body className="bg-black text-white font-figtree">
        <TopBannerComponent />
        <div className="xl:px-[211px]">
          <TopNavComponent />
          {children}
        </div>
      </body>
    </html>
  );
}
