import type { Metadata } from "next";
// import "./globals.css";
import "./output.css";
import { TopNavComponent } from "@/components/top-nav.component";
import { TopBannerComponent } from "@/components/top-banner.component";

export const metadata: Metadata = {
  title: "Fametonic Hero",
  description: "Generated by Netzet",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="bg-black text-white font-sans">
        <TopBannerComponent />
        <div className="xl:px-[211px]">
          <TopNavComponent />
          {children}
        </div>
      </body>
    </html>
  );
}
